on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
      - name: Print steps output
        run: echo '${{toJSON(steps.release.outputs)}}'
      - name: Save release version
        id: version
        run: |
          version=$(echo '${{toJSON(steps.release.outputs)}}' | jq -r '.["version"]')
          echo "version=$version" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.version }}
  build-and-push-image:
    name: build & push to GHCR
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.version != 'null' }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/app:${{ needs.release-please.outputs.version }},ghcr.io/${{ github.repository }}/app:latest
